spring:
  datasource:
    hikari:
      username: root
      password: root
    url: jdbc:mysql://localhost:3306/base_spring
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8080
  servlet:
    context-path: /api
  shutdown: graceful

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health
        info: /info
        prometheus: /prometheus
      exposure:
        include: health,info,prometheus
  server:
    port: 18443
  prometheus:
    metrics:
      export:
        enabled: true

info:
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'

jwt:
  token:
    secret: "f0Mgjk7DiCIxHs8zFMyE62Xy6QvIMol3"
    validity: 30000

bcrypt:
  version: $2a
  strength: -1
